# Generated by Django 2.0 on 2017-12-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20171210_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('name', models.CharField(max_length=255)),
                ('nose', models.CharField(max_length=255)),
                ('palate', models.CharField(max_length=255)),
                ('finish', models.CharField(max_length=255)),
                ('extra', models.CharField(max_length=255)),
            ],
        ),
    ]
